# 特徴量スケーリング

In [13]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

In [2]:
# データのロード
df = pd.read_csv('sample_data2.csv')

In [4]:
X = df[['space','age']]

In [8]:
#　標準化
scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)
pd.DataFrame(X_scaled, columns=X.columns)

      space       age
0 -1.134662 -0.806277
1 -0.941034  0.633504
2 -0.824857  1.353394
3 -0.747405  0.201569
4 -0.515051 -0.374343
5  0.065834 -1.094233
6  0.220736 -0.518321
7  0.491816 -0.950255
8  1.305055 -0.518321
9  2.079569  2.073284

In [12]:
# 線形回帰
model = LinearRegression()
y = df['rent']
model.fit(X_scaled, y)

LinearRegression()

In [15]:
#　正規化
model = MinMaxScaler()
scaler = model.fit(X)
X_scaled = scaler.transform(X)
pd.DataFrame(X_scaled, columns=X.columns)

      space       age
0  0.000000  0.090909
1  0.060241  0.545455
2  0.096386  0.772727
3  0.120482  0.409091
4  0.192771  0.227273
5  0.373494  0.000000
6  0.421687  0.181818
7  0.506024  0.045455
8  0.759036  0.181818
9  1.000000  1.000000